"""V4 Strategy Schema Models.

This package contains the Pydantic models for the V4 strategy document schema.
The schema supports:
- Simple and regime-adaptive strategies
- Multiple entry types (technical, event-driven, statistical, fundamental, alternative, compound)
- Complex position structures (single-leg, multi-leg, pairs, spreads)
- Position management and dynamic hedging
- Comprehensive data requirements specification
- Ingestion quality scoring and red flag detection
- Walk-forward validation results

Example usage:
    from research_system.schemas.v4 import V4Strategy, IngestionQuality, Validation

    # Parse a strategy from YAML
    import yaml
    with open("strategy.yaml") as f:
        data = yaml.safe_load(f)
    strategy = V4Strategy(**data)

    # Check ingestion quality
    quality = IngestionQuality(
        specificity=SpecificityScore(has_entry_rules=True, ...),
        trust_score=TrustScore(economic_rationale=25, ...),
    )
    decision = quality.compute_decision()
"""

# Strategy models
from research_system.schemas.v4.strategy import (
    # Enums
    AllocationMethod,
    AlternativeDataSource,
    AssetClass,
    AssumptionCategory,
    AuthorTrackRecord,
    CalendarDataType,
    Complexity,
    CompoundLogic,
    DayOfWeek,
    Direction,
    EdgeCategory,
    EntryType,
    EventType,
    ExitPriority,
    ExitType,
    ExpiryAction,
    ExpirySelection,
    FilterOperator,
    FundamentalFrequency,
    HypothesisType,
    InstrumentAssetType,
    InstrumentSelection,
    InstrumentSource,
    LineageRelationship,
    ManagementActionType,
    ManagementTriggerType,
    OptionType,
    OptionsDataType,
    PositionType,
    PriceDataType,
    ProvenanceConfidence,
    ProvenanceSource,
    RegimeAction,
    RegimeDetectionMethod,
    ResearchMethod,
    RiskCategory,
    RiskSeverity,
    SignalRefresh,
    SizingMethod,
    SourceType,
    StatisticalMetric,
    StopType,
    StrategyMode,
    StrategyStatus,
    StrikeSelection,
    TargetType,
    ThresholdDirection,
    TimingReference,
    TrailType,
    UniverseBase,
    UniverseType,
    # Metadata models
    ClaimedPerformance,
    SourceCredibility,
    StrategySource,
    StrategyLineage,
    StrategyTags,
    # Hypothesis models
    EdgeProvenance,
    StrategyEdge,
    Hypothesis,
    # Universe models
    StaticInstrument,
    FilterCriterion,
    UniverseRequirement,
    ResearchOutput,
    ResearchInputs,
    ResearchConfig,
    SignalFilter,
    Universe,
    # Entry models
    TechnicalConfig,
    EventTiming,
    EventConfig,
    StatisticalThreshold,
    StatisticalConfig,
    FundamentalConfig,
    AlternativeConfig,
    CompoundCondition,
    CompoundConfig,
    EntryFilter,
    EntryTiming,
    Entry,
    # Position models
    OptionParams,
    LegInstrument,
    LegAllocation,
    PositionLeg,
    PositionSizing,
    PositionConstraints,
    Position,
    # Exit models
    ExitPath,
    ExitFallback,
    Exit,
    # Position management models
    ManagementTrigger,
    ManagementAction,
    ManagementRule,
    PositionManagement,
    # Regime models
    RegimeIndicator,
    RegimeDetectionParams,
    RegimeDetection,
    RegimeMode,
    RegimeTransitions,
    Regimes,
    # Data requirements models
    PriceDataRequirement,
    FundamentalDataRequirement,
    OptionsDataRequirement,
    CalendarDataRequirement,
    AlternativeDataRequirement,
    DerivedCalculation,
    DataRequirements,
    # Assumptions and risks
    Assumption,
    Risk,
    # Backtest params
    BacktestParams,
    # Main strategy model
    V4Strategy,
)

# Ingestion models
from research_system.schemas.v4.ingestion import (
    RedFlagSeverity,
    IngestionDecision,
    SpecificityScore,
    TrustScore,
    RedFlag,
    IngestionQuality,
    HARD_RED_FLAGS,
    SOFT_RED_FLAGS,
    create_hard_red_flag,
    create_soft_red_flag,
)

# Validation models
from research_system.schemas.v4.validation import (
    ValidationStatus,
    VerificationTestStatus,
    VerificationTest,
    ValidationGates,
    ValidationResults,
    ValidationWindow,
    Validation,
    VERIFICATION_TESTS,
    create_verification_test,
    create_skipped_test,
)

__all__ = [
    # Strategy enums
    "AllocationMethod",
    "AlternativeDataSource",
    "AssetClass",
    "AssumptionCategory",
    "AuthorTrackRecord",
    "CalendarDataType",
    "Complexity",
    "CompoundLogic",
    "DayOfWeek",
    "Direction",
    "EdgeCategory",
    "EntryType",
    "EventType",
    "ExitPriority",
    "ExitType",
    "ExpiryAction",
    "ExpirySelection",
    "FilterOperator",
    "FundamentalFrequency",
    "HypothesisType",
    "InstrumentAssetType",
    "InstrumentSelection",
    "InstrumentSource",
    "LineageRelationship",
    "ManagementActionType",
    "ManagementTriggerType",
    "OptionType",
    "OptionsDataType",
    "PositionType",
    "PriceDataType",
    "ProvenanceConfidence",
    "ProvenanceSource",
    "RegimeAction",
    "RegimeDetectionMethod",
    "ResearchMethod",
    "RiskCategory",
    "RiskSeverity",
    "SignalRefresh",
    "SizingMethod",
    "SourceType",
    "StatisticalMetric",
    "StopType",
    "StrategyMode",
    "StrategyStatus",
    "StrikeSelection",
    "TargetType",
    "ThresholdDirection",
    "TimingReference",
    "TrailType",
    "UniverseBase",
    "UniverseType",
    # Strategy models
    "ClaimedPerformance",
    "SourceCredibility",
    "StrategySource",
    "StrategyLineage",
    "StrategyTags",
    "EdgeProvenance",
    "StrategyEdge",
    "Hypothesis",
    "StaticInstrument",
    "FilterCriterion",
    "UniverseRequirement",
    "ResearchOutput",
    "ResearchInputs",
    "ResearchConfig",
    "SignalFilter",
    "Universe",
    "TechnicalConfig",
    "EventTiming",
    "EventConfig",
    "StatisticalThreshold",
    "StatisticalConfig",
    "FundamentalConfig",
    "AlternativeConfig",
    "CompoundCondition",
    "CompoundConfig",
    "EntryFilter",
    "EntryTiming",
    "Entry",
    "OptionParams",
    "LegInstrument",
    "LegAllocation",
    "PositionLeg",
    "PositionSizing",
    "PositionConstraints",
    "Position",
    "ExitPath",
    "ExitFallback",
    "Exit",
    "ManagementTrigger",
    "ManagementAction",
    "ManagementRule",
    "PositionManagement",
    "RegimeIndicator",
    "RegimeDetectionParams",
    "RegimeDetection",
    "RegimeMode",
    "RegimeTransitions",
    "Regimes",
    "PriceDataRequirement",
    "FundamentalDataRequirement",
    "OptionsDataRequirement",
    "CalendarDataRequirement",
    "AlternativeDataRequirement",
    "DerivedCalculation",
    "DataRequirements",
    "Assumption",
    "Risk",
    "BacktestParams",
    "V4Strategy",
    # Ingestion
    "RedFlagSeverity",
    "IngestionDecision",
    "SpecificityScore",
    "TrustScore",
    "RedFlag",
    "IngestionQuality",
    "HARD_RED_FLAGS",
    "SOFT_RED_FLAGS",
    "create_hard_red_flag",
    "create_soft_red_flag",
    # Validation
    "ValidationStatus",
    "VerificationTestStatus",
    "VerificationTest",
    "ValidationGates",
    "ValidationResults",
    "ValidationWindow",
    "Validation",
    "VERIFICATION_TESTS",
    "create_verification_test",
    "create_skipped_test",
]
